### ISSUE TITLE
Inconsistent naming of predicates

### ISSUE THREAD

**Issue by andyjansson** [UbiquityDotNET/Llvm.NET#152]
This is a pretty minor issue, but nevertheless might be something to take note of. `IntPredicate` and `RealPredicate` have different naming schemes from each other.  The latter uses `Than` while the former does not. For example: `IntPredicate.SignedLess` & `RealPredicate.OrderedAndLessThan`. 

Additionally, the documentation for `RealPredicate` seem to be suffering from a copy-paste error: 
"Predicate enumeration for **integer** comparison".

**Comment by smaillet** [comment]
The names are based on the actual LLVM naming under the hood, which are not consistent themselves. However since the .NET names are a remapping to .NET anyway there's no reason they can't be made more consistent except that it would be a breaking change. That would need to happen on a major release boundary. 

The docs are something that can be updated without breaking anything. (Though not currently without a new release since the docs are generated as part of the build to ensure they are current with a particular build/release)
