### ISSUE TITLE
NuGet package gone missing

### ISSUE THREAD

**Issue by JesperTreetop** [UbiquityDotNET/Llvm.NET#160]
The NuGet package linked in the readme [404s](https://www.nuget.org/packages/Ubiquity.NET.Llvm/) as of right now. Has it been renamed?

**Comment by smaillet** [comment]
Sort of, the develop branch is for VNEXT (e.g. LLVM 10) where the names of packages are all changing. Master branch has the current released code and the nuget links for that shoudl still be good. The default branch is set to develop so that PRs etc.. go to that branch (PRs never go to master - it always reflects only released code) Sorry for the confusion but it's only temporary until there's an official release of support for LLVM 10, which is coming soon. (LLVM10 itself only just released this week)

**Comment by smaillet** [comment]
The 10.0.0-alpha release NUGET package is now available under the new name.
