### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by matty-hall** [UbiquityDotNET/Llvm.NET#66]
I don't have VS2017 and cannot open the project. It would be *really* helpful if the project included a link on the main page for downloading the latest version of all of this. You have a link to something called appveyor, but you don't describe what that is, or how I can get the latest binaries from there.

**Comment by smaillet** [comment]
You can get the binaries from the AppVeyor NuGet feed. You need to setup your NuGet Client to point to:
https://ci.appveyor.com/NuGet/Ubiquity.Llvm.NET
So that Nuget can see the built binaries.

See
[NuGet documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) for general use and [Visual Studio Documentation](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#package-sources) for specifics in Visual Studio.

As of yet there hasn't been a published release to official NuGet though if that's major concern we can look into publishing the V5.x binaries. Ultimately the plan was to publish to Nuget with 6.0 but managing the native Llvm.Libs and their size is problematic so the means of getting the native libs built that this project depends on is currently in-flux for 6.0. Once that gets straightened out the 6.0 bits should be ready for release.

**Comment by btbaggin** [comment]
I pointed NuGet to the URL you provided and it can find this project, but when I try to add it, it says "Unable to resolve dependency 'CSemVer.Build.Tasks'".
Can you provide me any guidance on where I can get the that project? 
The github page doesn't list any NuGet packages.

**Comment by smaillet** [comment]
All of the UbiquityDotNET projects currently use AppVeyor to build the projects. Each has a unique AppVeyor nuget feed for the components. Until they are officially released on the general Nuget feed, the simplest way to get them is to use a nuget.config to add the feeds for your project. An example of this can be found in the [Nuget.Config](https://github.com/UbiquityDotNET/Llvm.NET/blob/master/NuGet.Config) file from this repository. 


The reason for not publishing to Nuget is that theses support packages have undergone significant changes while working to stabilize and utilize them for this project. As they have become more stable it's probably ok to make them more broadly available. I just haven't had the time to do that yet. Though I've set aside some time to update things for the latest LLVM 7.0 bits so I should be able to take care of Getting all of these properly onto NuGet for that version.

**Comment by smaillet** [comment]
Public NuGet for released versions is now fully supported and integrated into the GH Actions automated build.
